doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Api:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Api/Model'
                prefix: 'App\Api\Model'
                alias: Api
            Showroom:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Showroom/Model'
                prefix: 'App\Showroom\Model'
                alias: Showroom
        resolve_target_entities:
            Symfony\Component\Security\Core\User\UserInterface: App\Api\Model\Entity\User