doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'ApiDoctrineMigrations': '%kernel.project_dir%/src/Api/Infrastructure/Migrations'
        'ShowroomDoctrineMigrations': '%kernel.project_dir%/src/Showroom/Infrastructure/Migrations'
