#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
  path: /register
  controller: App\Api\Infrastructure\Controller\AuthController::register
  methods: [ 'POST' ]

get_authentication_token:
  path: /authentication_token
  methods: [ 'POST' ]

list_car_manufacturer_brands:
  path: customer_area/cars/brands/
  controller: App\Showroom\Infrastructure\Controller\TradeController::getCarBrands
  methods: [ 'GET' ]

list_car_models_per_brand:
  path: customer_area/cars/{brand}
  controller: App\Showroom\Infrastructure\Controller\TradeController::getBrandModels
  methods: [ 'GET' ]

sell_car_for_trade_in:
  path: customer_area/sell_car
  controller: App\Showroom\Infrastructure\Controller\TradeController::tradeInCustomerCar
  methods: [ 'POST' ]

buy_car_with_surcharge:
  path: customer_area/buy_car_with_surcharge
  controller: App\Showroom\Infrastructure\Controller\TradeController::sellCarForTradeIn
  methods: [ 'POST' ]

list_customers:
  path: manager_area/customers
  controller: App\Showroom\Infrastructure\Controller\CustomerManagementController::list
  methods: [ 'GET' ]

delete_customer:
  path: manager_area/customers/{customer_id}
  controller: App\Showroom\Infrastructure\Controller\CustomerManagementController::delete
  methods: [ 'DELETE' ]
  requirements:
    customer_id: \d+