#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
  path: /register
  controller: App\Api\Infrastructure\Controller\AuthController::register
  methods: [ 'POST' ]

get_authentication_token:
  path: /authentication_token
  methods: [ 'POST' ]

list_car_manufacturer_brands:
  path: client_section/cars/brands/
  controller: App\Showroom\Infrastructure\Controller\TradeController::getCarBrands
  methods: GET

list_car_models_per_brand:
  path: client_section/cars/{brand}
  controller: App\Showroom\Infrastructure\Controller\TradeController::getBrandModels
  methods: GET

sell_car_for_trade_in:
  path: client_section/sell_car
  controller: App\Showroom\Infrastructure\Controller\TradeController::tradeInClientCar
  methods: POST